package com.park.welstory.wooriportal.saramin.enumlist.JobCode;

import lombok.Getter;

@Getter
public enum Code6Medical {

    INSURANCE_REVIEW_AGENT(2236, "보험심사청구사"),
    CAREGIVER(501, "간병인"),
    FUNCTIONAL_TEST(523, "기능검사"),
    FAMILY_MEDICINE(551, "가정의학과"),
    ENDOSCOPY_ROOM(587, "내시경실"),
    TWO_SHIFT(623, "2교대"),
    DENTAL_HYGIENIST(461, "치과위생사"),
    AMBULANCE_DRIVER(502, "구급차기사"),
    DRESSING_ASSISTANT(524, "드레싱보조"),
    INFECTIOUS_INTERNAL_MEDICINE(552, "감염내과"),
    HOSPICE(588, "호스피스"),
    THREE_SHIFT(624, "3교대"),
    NURSE(462, "간호사"),
    SCALP_CARE_SPECIALIST(503, "두피관리사"),
    HAIR_TRANSPLANT(525, "모발이식"),
    ORAL_MEDICINE(553, "구강내과"),
    RECOVERY_ROOM(589, "회복실"),
    NIGHT_DUTY(625, "당직"),
    PLAY_THERAPIST(463, "놀이치료사"),
    WARD_CAREGIVER(504, "병동보호사"),
    HOME_NURSING(526, "방문간호"),
    ORAL_SURGERY(554, "구강외과"),
    NEONATAL_ROOM(590, "신생아실"),
    D_KEEP(626, "D-Keep"),
    MANUAL_THERAPIST(464, "도수치료사"),
    HOSPITAL_ACCOUNTING(505, "병원경리"),
    HOSPITAL_MANAGEMENT(527, "병원경영"),
    INTERNAL_MEDICINE(555, "내과"),
    EMERGENCY_ROOM(591, "응급실"),
    DE(627, "DE"),
    ANESTHESIA_NURSE(465, "마취간호사"),
    HOSPITAL_GENERAL_AFFAIRS(506, "병원총무"),
    HOSPITAL_ADMIN(528, "병원관리"),
    ENDOCRINE_INTERNAL_MEDICINE(556, "내분비내과"),
    ARTIFICIAL_KIDNEY_ROOM(592, "인공신장실"),
    DN(628, "DN"),
    PHYSICAL_THERAPIST(466, "물리치료사"),
    HOSPITAL_COORDINATOR(507, "병원코디네이터"),
    HEALTH_DIAGNOSIS(529, "보건진단"),
    COLORECTAL_SURGERY(557, "대장항문외과"),
    ICU(593, "중환자실"),
    E_KEEP(629, "E-Keep"),
    ART_THERAPIST(467, "미술치료사"),
    HOSPITAL_ADMIN_OFFICER(508, "병원행정사"),
    SURGERY(530, "수술"),
    ANESTHESIOLOGY(558, "마취통증의학과"),
    TREATMENT_ROOM(594, "처치실"),
    EN(630, "EN"),
    RADIOLOGIST(468, "방사선사"),
    HEALTH_MANAGER(509, "보건관리자"),
    SURGERY_ASSISTANT(531, "수술보조"),
    PATHOLOGY(559, "병리과"),
    INJECTION_ROOM(595, "주사실"),
    N_KEEP(631, "N-Keep"),
    OCCUPATIONAL_HEALTH_NURSE(469, "산업간호사"),
    OBESITY_MANAGER(510, "비만관리사"),
    SPORTS_MASSAGE(532, "스포츠마사지"),
    UROLOGY(560, "비뇨기과"),
    IMAGING_ROOM(596, "촬영실"),
    S_KEEP(632, "S-Keep"),
    COUNSELING_NURSE(470, "상담간호사"),
    COUNSELING_DIRECTOR(511, "상담실장"),
    OUTPATIENT(533, "외래"),
    OBSTETRICS_GYNECOLOGY(561, "산부인과"),
    PRIVATE_CLINIC(597, "개인병원"),
    HEAD_NURSE(471, "수간호사"),
    PSYCHOMOTOR_THERAPIST(512, "심리운동사"),
    MEDICAL_AFFAIRS(534, "원무"),
    PLASTIC_SURGERY(562, "성형외과"),
    HEALTH_SCREENING_CENTER(598, "검진센터"),
    VETERINARIAN(472, "수의사"),
    PHARMACY_COMPUTER_OPERATOR(513, "약국전산원"),
    MEDICAL_IMAGING(535, "의료영상"),
    PEDIATRICS(563, "소아과"),
    GERIATRIC_HOSPITAL(599, "노인전문병원"),
    VET_TECHNICIAN(473, "수의테크니션"),
    NUTRITIONIST(514, "영양사"),
    MEDICAL_CLERICAL(536, "의약사무"),
    GASTROENTEROLOGY(564, "소화기내과"),
    UNIVERSITY_HOSPITAL(600, "대학병원"),
    PSYCHOTHERAPIST(474, "심리치료사"),
    CARE_WORKER(515, "요양보호사"),
    CLINICAL_TRIAL(537, "임상시험"),
    CARDIOLOGY(565, "순환기내과"),
    ANIMAL_HOSPITAL(601, "동물병원"),
    REVIEW_NURSE(475, "심사간호사"),
    EXERCISE_PRESCRIPTIONIST(516, "운동처방사"),
    INPATIENT_MANAGEMENT(538, "입원관리"),
    NEUROSURGERY(566, "신경외과"),
    HEALTH_CENTER(602, "보건소"),
    PHARMACIST(476, "약사"),
    SANITARIAN(517, "위생사"),
    RECEPTION_RESERVATION(539, "접수예약"),
    NEPHROLOGY(567, "신장내과"),
    OBESITY_CLINIC(603, "비만클리닉"),
    SPEECH_THERAPIST(477, "언어치료사"),
    PARAMEDIC(518, "응급구조사"),
    PHARMACEUTICAL_QA(540, "제약QA"),
    OPHTHALMOLOGY(568, "안과"),
    POSTPARTUM_CENTER(604, "산후조리원"),
    EXERCISE_THERAPIST(478, "운동치료사"),
    HEALTH_INFORMATION_MANAGER(519, "보건의료정보관리사"),
    DISPENSING_ASSISTANT(541, "조제보조"),
    ALLERGOLOGY(569, "알레르기내과"),
    CARDIOVASCULAR_CENTER(605, "심혈관센터"),
    MUSIC_THERAPIST(479, "음악치료사"),
    PROSTHETICS_ORTHOTICS(520, "의지보조기기사"),
    CLINICAL_ASSISTANCE(542, "진료보조"),
    PHARMACY_DEPARTMENT(570, "약제과"),
    CHILDREN_HOSPITAL(606, "아동병원"),
    MEDICAL_ENGINEER(480, "의공기사"),
    PSYCHIATRIC_CAREGIVER(521, "정신과보호사"),
    BLOOD_DRAW(543, "채혈"),
    RADIOLOGY(571, "영상의학과"),
    CANCER_CENTER(607, "암센터"),
    DOCTOR(481, "의사"),
    MR(522, "MR"),
    PRESCRIPTION(544, "처방"),
    GENERAL_SURGERY(572, "외과"),
    PHARMACY(608, "약국"),
    COGNITIVE_THERAPIST(482, "인지치료사"),
    ACUPUNCTURE_ASSISTANT(545, "침구실보조"),
    ENT(573, "이비인후과"),
    WOMENS_HOSPITAL(609, "여성병원"),
    CLINICAL_PATHOLOGIST(483, "임상병리사"),
    BEHAVIORAL_THERAPY(546, "행동치료"),
    REHABILITATION_MEDICINE(574, "재활의학과"),
    WOMENS_CLINIC(610, "여성의원"),
    CLINICAL_PSYCHOLOGIST(484, "임상심리사"),
    PATIENT_GUIDANCE(547, "환자안내"),
    PSYCHIATRY(575, "정신과"),
    NURSING_HOME(611, "요양병원"),
    OCCUPATIONAL_THERAPIST(485, "작업치료사"),
    PATIENT_TRANSPORT(548, "환자이송"),
    ORTHOPEDICS(576, "정형외과"),
    GENERAL_HOSPITAL_WARD(612, "일반병원"),
    REHABILITATION_THERAPIST(486, "재활치료사"),
    RA(549, "RA"),
    OCCUPATIONAL_ENVIRONMENTAL_MEDICINE(577, "직업환경의학과"),
    REHABILITATION_CENTER(613, "재활센터"),
    RESIDENT_DOCTOR(487, "전공의"),
    HISTOPATHOLOGY(550, "조직병리"),
    LABORATORY_MEDICINE(578, "진단검사의학과"),
    PSYCHIATRIC_HOSPITAL(614, "정신병원"),
    SPECIALIST(488, "전문의"),
    DENTAL(579, "치과"),
    GENERAL_HOSPITAL(615, "종합병원"),
    CHARGE_NURSE(489, "책임간호사"),
    PAIN_MEDICINE(580, "통증의학과"),
    DAY_NIGHT_CARE_CENTER(616, "주야간보호센터"),
    AUDIOLOGIST(490, "청능사청각사"),
    DERMATOLOGY(581, "피부과"),
    SPINE_HOSPITAL(617, "척추병원"),
    ULTRASONOGRAPHER(491, "초음파사"),
    ORIENTAL_MEDICINE_DEPT(582, "한방과"),
    DENTAL_HOSPITAL(618, "치과병원"),
    DENTAL_TECHNICIAN(492, "치기공사"),
    NUCLEAR_MEDICINE(583, "핵의학과"),
    DENTAL_CLINIC(619, "치과의원"),
    HERBAL_PHARMACIST(493, "한약사"),
    HEMATOLOGY_ONCOLOGY(584, "혈액종양내과"),
    ORIENTAL_MEDICINE_HOSPITAL(620, "한방병원"),
    ORIENTAL_MEDICINE_DOCTOR(494, "한의사"),
    RESPIRATORY_MEDICINE(585, "호흡기내과"),
    ORIENTAL_MEDICINE_CLINIC(621, "한의원"),
    CRA(495, "CRA(임상연구원)"),
    THORACIC_SURGERY(586, "흉부외과"),
    BLOOD_CENTER(622, "혈액원"),
    CRC(496, "CRC(임상시험코디네이터)"),
    CRM(497, "CRM(임상연구전문가)"),
    QPS_NURSE(498, "QPS간호사"),
    OPTICIAN(499, "안경사"),
    NURSING_ASSISTANT(500, "간호조무사");

    private final int code;
    private final String name;

    Code6Medical(int code, String name) {
        this.code = code;
        this.name = name;
    }

    public static Code6Medical fromCode(int code) {
        for (Code6Medical c : values()) {
            if (c.code == code) return c;
        }
        throw new IllegalArgumentException("Unknown code: " + code);
    }
}