package com.park.welstory.wooriportal.saramin.enumlist.JobCode;

import lombok.Getter;

@Getter
public enum Code10Service {

    CHEF(2214, "요리사"),
    NUTRITIONIST(2216, "영양사"),
    PATISSIER(2228, "파티쉐"),
    STORE_MANAGEMENT(2202, "매장관리"),
    CLEANING(2207, "청소"),
    CAR_MAINTENANCE(2209, "자동차정비"),
    FACILITY_MANAGEMENT(2235, "시설관리"),
    SKIN_CARE_SPECIALIST(858, "피부관리사"),
    ROOM_MANAGEMENT(929, "객실관리"),
    AIRPORT(964, "공항"),
    HOUSEKEEPER(859, "가사도우미"),
    CUSTOMER_GUIDANCE(930, "고객안내"),
    MANAGEMENT_OFFICE(965, "관리사무소"),
    METER_READER(860, "검침원"),
    CUSTOMER_SERVICE(931, "고객응대"),
    CAFETERIA(966, "급식소"),
    SECURITY_GUARD(861, "경비원"),
    POLISHING(932, "광택"),
    NAIL_SHOP(967, "네일샵"),
    SECURITY_SUPERVISOR(862, "경비지도사"),
    MACHINERY_REPAIR(933, "기계수리"),
    LARGE_MART(968, "대형마트"),
    BODYGUARD(863, "경호원"),
    DIET(934, "다이어트"),
    DRESS_SHOP(969, "드레스샵"),
    TOUR_GUIDE(864, "관광가이드"),
    ANIMAL_MANAGEMENT(935, "동물관리"),
    RESORT(970, "리조트"),
    TOURIST_INTERPRETER(865, "관광통역안내사"),
    ANIMAL_FUNERAL(936, "동물장례"),
    BEAUTY_SALON(971, "미용실"),
    NARRATOR(866, "나레이터"),
    ROUNDING(937, "라운딩"),
    DEPARTMENT_STORE(972, "백화점"),
    NAIL_ARTIST(867, "네일리스트"),
    RENTAL(938, "렌탈"),
    BOOKSTORE(973, "서점"),
    SCALP_CARE_SPECIALIST(868, "두피관리사"),
    MASSAGE(939, "마사지"),
    RESTAURANT(974, "식당"),
    RIDER(869, "라이더(배달원)"),
    MAKEUP(940, "메이크업"),
    ESTHETIC_SPA(975, "에스테틱스파"),
    ROOM_MAID(870, "룸메이드"),
    DUTY_FREE_DELIVERY(941, "면세품인도"),
    FERRY(976, "여객선"),
    STORE_MANAGER(871, "매장매니저"),
    TICKETING(942, "발권"),
    TRAVEL_AGENCY(977, "여행사"),
    TICKET_CHECKER(872, "매표검표"),
    SECURITY_PATROL(943, "방범"),
    CINEMA(978, "영화관"),
    HAIR_STYLIST(873, "미용사"),
    FACILITY_INSPECTION(944, "설비점검"),
    WEDDING_STUDIO(979, "웨딩스튜디오"),
    JANITOR(874, "미화원"),
    LAUNDRY(945, "세탁"),
    WEDDING_HALL(980, "웨딩홀"),
    BARISTA(875, "바리스타"),
    DISINFECTION(946, "소독"),
    FUNERAL_HALL(981, "장례식장"),
    BARTENDER(876, "바텐더"),
    EYELASH(947, "속눈썹"),
    KITCHEN(982, "주방"),
    VALET_PARKING(877, "발레파킹"),
    MEAL_MANAGEMENT(948, "식단관리"),
    GAS_STATION(983, "주유소"),
    BELLMAN_DOORMAN(878, "벨멘도어맨"),
    WINDOW_TINTING(949, "썬팅"),
    CASINO(984, "카지노"),
    SECURITY_PERSONNEL(879, "보안요원"),
    FEE_SETTLEMENT(950, "요금정산"),
    CAFE(985, "카페"),
    SOUS_CHEF(880, "부주방장"),
    CLOTHING_REPAIR(951, "의류수선"),
    CONDO(986, "콘도"),
    BEAUTY_MANAGER(881, "뷰티매니저"),
    INTERNET_INSTALLATION(952, "인터넷설치"),
    KIDS_CAFE(987, "키즈카페"),
    POSTPARTUM_HELPER(882, "산후도우미"),
    CAR_PAINTING(953, "자동차도장"),
    AIRLINE(988, "항공사"),
    CAR_WASHER(883, "세차원"),
    CAR_TUNING(954, "자동차튜닝"),
    HOTEL(989, "호텔"),
    SOMMELIER(884, "소믈리에"),
    RECEPTION_RESERVATION(955, "접수예약"),
    STYLIST(885, "스타일리스트"),
    PRINTING_BINDING(956, "출력제본복사"),
    FLIGHT_ATTENDANT(886, "승무원"),
    CATERING(957, "케이터링"),
    AQUARIST(887, "아쿠아리스트"),
    PENSION_MANAGEMENT(958, "펜션관리"),
    INFORMATION_DESK(888, "안내데스크"),
    FRONT_DESK(959, "프론트"),
    SAFETY_OFFICER(889, "안전요원"),
    FILTER_REPLACEMENT(960, "필터교체"),
    BREWER(890, "양조사"),
    PEST_CONTROL(961, "해충방제"),
    WAXER(891, "왁서"),
    CASH_ESCORT(962, "현금호송"),
    WEDDING_PLANNER(892, "웨딩플래너"),
    LPG_CHARGING(963, "LPG충전"),
    CHILDCARE_HELPER(893, "육아도우미"),
    MOVE_IN_HELPER(894, "입주도우미"),
    FUNERAL_DIRECTOR(895, "장례지도사"),
    MAINTENANCE_TECHNICIAN(896, "정비기사"),
    BAKER(897, "제과제빵사"),
    COOK(898, "조리사"),
    KITCHEN_ASSISTANT(899, "주방보조"),
    HEAD_CHEF(900, "주방장"),
    GAS_STATION_ATTENDANT(901, "주유원"),
    PARKING_ATTENDANT(902, "주차요원"),
    MANAGER(903, "지배인"),
    GROUND_STAFF(904, "지상직"),
    VEHICLE_ASSISTANT(905, "차량도우미"),
    BODY_SHAPE_MANAGER(906, "체형관리사"),
    CAFE_MANAGER(907, "카페매니저"),
    CASHIER(908, "캐셔"),
    COMMUNITY_MANAGER(909, "커뮤니티매니저"),
    COUPLE_MANAGER(910, "커플매니저"),
    CAR_TRANSPORT_DRIVER(911, "탁송기사"),
    THERAPIST(912, "테라피스트"),
    PROMOTER(913, "프로모터"),
    FLORIST(914, "플로리스트"),
    HOUSEMAN(915, "하우스맨"),
    COMMENTATOR(916, "해설가"),
    EVENT_HELPER(917, "행사도우미"),
    HOTELIER(918, "호텔리어"),
    HALL_MANAGER(919, "홀매니저"),
    HALL_SERVER(920, "홀서빙"),
    AS_TECHNICIAN(921, "AS기사"),
    APPLIANCE_INSTALLATION(922, "가전제품설치"),
    PET_GROOMER(923, "애견미용"),
    PET_TRAINER(924, "애견훈련"),
    PARTY_PLANNER(925, "파티플래너"),
    FOOD_STYLIST(926, "푸드스타일리스트"),
    GRO_CONCIERGE(927, "GRO(컨시어지)"),
    GEMOLOGIST(928, "보석감정사");

    private final int code;
    private final String name;

    Code10Service(int code, String name) {
        this.code = code;
        this.name = name;
    }

    public static Code10Service fromCode(int code) {
        for (Code10Service c : values()) {
            if (c.code == code) return c;
        }
        throw new IllegalArgumentException("Unknown code: " + code);
    }
}