package com.park.welstory.wooriportal.saramin.enumlist.JobCode;

import lombok.Getter;

@Getter
public enum Code8SalesRetail {

    SALES(2203, "영업"),
    SALES_PLANNING(2208, "영업기획"),
    SECURITY_SOLUTION_SALES(2241, "보안솔루션영업"),
    CUSTOMS_BROKER(689, "관세사"),
    B2B(754, "B2B"),
    CUSTOMS_CLERK(690, "관세사무원"),
    B2C(755, "B2C"),
    INTERNATIONAL_TRADER(691, "국제무역사"),
    FRANCHISE_MANAGEMENT(756, "가맹점관리"),
    TECHNICAL_SALES(692, "기술영업"),
    FRANCHISE_SALES(757, "가맹점영업"),
    TRADE_ACCOUNTING(693, "무역경리"),
    CLIENT_MANAGEMENT(758, "거래처관리"),
    TRADE_CLERK(694, "무역사무원"),
    CLIENT_DELIVERY(759, "거래처납품"),
    TRADE_BROKER(695, "무역중개인"),
    CLIENT_SALES(760, "거래처영업"),
    TRADE_MR(696, "무역MR"),
    CUSTOMER_MANAGEMENT(761, "고객관리"),
    BONDED_AGENT(697, "보세사"),
    PUBLIC_SALES(762, "공공영업"),
    SHOP_MASTER(698, "샵마스터"),
    CUSTOMS_REFUND(763, "관세환급"),
    SALES_MANAGEMENT(699, "영업관리"),
    CORPORATE_SALES(764, "기업영업"),
    SALES_SUPPORT(700, "영업지원"),
    RENTAL_SALES(765, "렌탈영업"),
    SALES_STAFF(701, "영업직"),
    MART_SALES(766, "마트영업"),
    SALES_MD(702, "영업MD"),
    STORE_MANAGEMENT(767, "매장관리"),
    ORIGIN_MANAGER(703, "원산지관리사"),
    MEDIA_SALES(768, "매체영업"),
    CAR_DEALER(704, "자동차딜러"),
    REVENUE_MANAGEMENT(769, "매출관리"),
    CASHIER(705, "캐셔"),
    TRADE_TRANSACTION(770, "무역거래"),
    SALES_PERSON(706, "판매직"),
    TRADE_ENGLISH(771, "무역영어"),
    FORWARDER(707, "포워더"),
    BUYER_MANAGEMENT(772, "바이어발굴관리"),
    FURNITURE_SALES(708, "가구판매"),
    DEPARTMENT_STORE_SALES(773, "백화점영업"),
    ELECTRONICS_SALES(709, "가전판매"),
    VENDOR_MANAGEMENT(774, "벤더관리"),
    HEALTH_FOOD_SALES(710, "건강식품판매"),
    PARTS_EXPORT(775, "부품수출"),
    CONSTRUCTION_SALES(711, "건설영업"),
    SHOPPING_MALL_MANAGEMENT(776, "쇼핑몰관리"),
    AD_SALES(712, "광고영업"),
    ORDER_MANAGEMENT(777, "수발주"),
    JEWELRY_SALES(713, "귀금속판매"),
    IMPORT_EXPORT(778, "수출입"),
    MACHINERY_SALES(714, "기계판매"),
    PERFORMANCE_MANAGEMENT(779, "실적관리"),
    NETWORK_SALES(715, "네트워크영업"),
    OUTLET_SALES(780, "아울렛영업"),
    DOOR_TO_DOOR_SALES(716, "방문판매"),
    TRAVEL_AGENCY_SALES(781, "여행사영업"),
    REAL_ESTATE_SALES(717, "부동산영업"),
    ONLINE_SALES(782, "온라인영업"),
    FUNERAL_SERVICE_SALES(718, "상조영업"),
    DISTRIBUTION_SALES(783, "유통영업"),
    SOLUTION_TECH_SALES(719, "솔루션기술영업"),
    LONG_TERM_RENTAL_SALES(784, "장기렌트영업"),
    SYSTEM_SALES(720, "시스템영업"),
    STORE_DEVELOPMENT(785, "점포개발"),
    FOOD_BEVERAGE_SALES(721, "식품음료영업"),
    SETTLEMENT_MANAGEMENT(786, "정산관리"),
    FOOD_BEVERAGE_RETAIL(722, "식품음료판매"),
    ORDER_PROCESSING(787, "주문관리"),
    SALES_MARKETING(723, "영업마케팅"),
    DISPLAY_MANAGEMENT(788, "진열관리"),
    SALES_STRATEGY(724, "영업전략"),
    CUSTOMS_CLEARANCE(789, "통관"),
    SALES_PROMOTION(725, "영업판촉"),
    ACADEMY_SALES(790, "학원영업"),
    ONLINE_RETAIL(726, "온라인판매"),
    OVERSEAS_SALES_MANAGEMENT(791, "해외영업관리"),
    MEDICAL_DEVICE_SALES(727, "의료기기영업"),
    OVERSEAS_SALES_SUPPORT(792, "해외영업지원"),
    CLOTHING_TRADE(728, "의류무역"),
    MOBILE_PHONE_SALES(793, "핸드폰영업"),
    CLOTHING_RETAIL(729, "의류판매"),
    HOME_SHOPPING_SALES(794, "홈쇼핑영업"),
    CAR_SALES(730, "자동차영업"),
    FTA(795, "FTA"),
    MATERIAL_SALES(731, "자재판매"),
    HW(796, "HW"),
    SUNDRY_GOODS_SALES(732, "잡화판매"),
    LC(797, "LC(신용장)"),
    EQUIPMENT_SALES(733, "장비영업"),
    SW(798, "SW"),
    MEAT_RETAIL(734, "정육판매"),
    PHARMACEUTICAL_SALES(735, "제약영업"),
    LIQUOR_SALES(736, "주류영업"),
    LIQUOR_RETAIL(737, "주류판매"),
    LIVESTOCK_RETAIL(738, "축산물판매"),
    COMPUTER_RETAIL(739, "컴퓨터판매"),
    TIRE_RETAIL(740, "타이어판매"),
    TELECOM_DEVICE_RETAIL(741, "통신기기판매"),
    TICKET_SALES(742, "티켓판매"),
    AIR_TRADE(743, "항공무역"),
    SEA_TRADE(744, "해상무역"),
    OVERSEAS_MARKET_DEVELOPMENT(745, "해외시장개척"),
    OVERSEAS_SALES(746, "해외영업"),
    MOBILE_PHONE_RETAIL(747, "핸드폰판매"),
    HOTEL_SALES(748, "호텔영업"),
    COSMETICS_SALES(749, "화장품영업"),
    COSMETICS_RETAIL(750, "화장품판매"),
    IT_SALES(751, "IT영업"),
    SI_SALES(752, "SI영업"),
    SECURITIES_SALES(753, "증권영업");

    private final int code;
    private final String name;

    Code8SalesRetail(int code, String name) {
        this.code = code;
        this.name = name;
    }

    public static Code8SalesRetail fromCode(int code) {
        for (Code8SalesRetail c : values()) {
            if (c.code == code) return c;
        }
        throw new IllegalArgumentException("Unknown code: " + code);
    }
}